"""LiteParse adapter tests without downloading the external package."""

import sys
import types

from parsers.liteparse_parser import LiteParseParser


def test_liteparse_adapter_returns_markdown(monkeypatch, tmp_path):
    class FakeLiteParse:
        def __init__(self, **kwargs):
            self.kwargs = kwargs
        def parse(self, _):
            return types.SimpleNamespace(
                text="# Chapter\n\nText",
                pages=[types.SimpleNamespace(page_num=1, text_items=[types.SimpleNamespace(text="Page one")])],
            )

    monkeypatch.setitem(sys.modules, "liteparse", types.SimpleNamespace(LiteParse=FakeLiteParse))
    pdf = tmp_path / "book.pdf"
    pdf.write_bytes(b"fake")
    parser = LiteParseParser()
    assert parser.parse(str(pdf)) == "# Chapter\n\nText"
    assert parser.last_page_text == {1: "Page one"}


def test_liteparse_fixes_reversed_arabic_headings_and_body(monkeypatch, tmp_path):
    # Simulated reversed Arabic Markdown generated by LTR PDFium spatial traversal
    reversed_md = (
        "<!-- page: 1 -->\n"
        "# ةكرحلاو ةماعدلا :لوألا لصفلا\n\n"
        "ةيميلعتلا ةداملا يف تامولعم.\n\n"
        "## بيكرتلا :لوألا سردلا"
    )

    class FakeLiteParseArabic:
        def __init__(self, **kwargs):
            pass
        def parse(self, _):
            return types.SimpleNamespace(
                text=reversed_md,
                pages=[types.SimpleNamespace(page_num=1, markdown=reversed_md)],
            )

    monkeypatch.setitem(sys.modules, "liteparse", types.SimpleNamespace(LiteParse=FakeLiteParseArabic))
    pdf = tmp_path / "arabic_book.pdf"
    pdf.write_bytes(b"dummy")

    parser = LiteParseParser()
    repaired_output = parser.parse(str(pdf))

    # Assert that the headings have been reordered correctly to RTL
    assert "الفصل الأول: الدعامة والحركة" in repaired_output
    assert "الدرس الأول: التركيب" in repaired_output

